### ISSUE TITLE
Update Font Awesome Version

### ISSUE THREAD

**Issue by mkrdip** [ideag/tiny_coffee#13]
Then current version (4.0.3) of font-awesome in plugin creates issues with older versions of few browsers (Opera, Chrome). e.g: Coffee Icon not showing 

By updating font-awesome version (4.3.0), resolves this issue.

**Comment by ideag** [comment]
Hi, and thanks for the PR. I agree about the issue, but I am working on a more permanent solution for it - I want FontAwesome to be automatically updated whenever there is a new version.

**Comment by mkrdip** [comment]
I think you can make a quick release for now so that other users can resolves their issue. And I'm very much glad that you've a powerful alternative solution with a major release.

**Comment by ideag** [comment]
The serious solution was coming really soon, so I was reluctant make a release just to bump version.   Fixed now.
